---
base_packages:
  - curl
  - htop
  - vim
  - rsync
  - python3
  - python3-pip
  - wget
  - tree
  - unzip
  - haproxy

minecraft_version: "empty"
minecraft_papermc_build: ""
minecraft_java_args: ""
